### ISSUE TITLE
REDESIGN-16 - Switch to another css framework

### ISSUE THREAD

**Issue by jayjayjpg** [biojs/biojs.net#16]
Although Bootstrap is very common easy-to-use nowadays, we could think about switching to another css framework to give the site a new fresh design from scratch. 

A couple of interesting frameworks I can suggest are
- [Materialize](http://materializecss.com/) - offers similar to BS its own composable css classes and js components for common UI elements. Features Google Material Design like styling, Flexbox styled elements and precompilation with SASS
- [Foundation](http://foundation.zurb.com/) quite extensive, and well-developed CSS framework with strong focus on responsive layouts

**Comment by jayjayjpg** [comment]
@DennisSchwartz What do you think about Materialize? I'll play a bit with it on my fork and can show you something in the next days if you'd like - pretty neat design base work in my opinion! Happy to hear about your thoughts

**Comment by DennisSchwartz** [comment]
@jessica-jordan I've heard about it before and I think it looks quite nice. That will distinguish us at least a little bit from the millions of bootstrap sites out there. Is it as easy to use as bootstrap?

**Comment by jayjayjpg** [comment]
Merged into my fork, biojs.net merge tbd

**Comment by jayjayjpg** [comment]
closed by #23
