### ISSUE TITLE
REDESIGN-16 - Move Site to A New Drupal Install

### ISSUE THREAD

**Issue by jayjayjpg** [biojs/biojs.net#17]
To make content management even more approachable to its editors we plan to use a CMS solution for biojs.net.

One option would be to install Drupal and build biojs.net on top of that.
There might be a possibility to rather easily create a new Drupal instance for biojs.net once the new TGAC page (which will also be Drupal based) is up. 

Let's discuss the time point when to migrate the page to Drupal.

**Comment by jiku** [comment]
Why Drupal and not a [Node-based CMS](https://www.npmjs.com/browse/keyword/cms)? Could help for integrating with BioJS, dat, etc?

**Comment by manuelcorpas** [comment]
Drupal is a potential choice because we have already expertise on it and it
is easy to maintain and add content.

Do you have some specific Node-based suggestions?

Cheers
Manny

## 

Dr Manuel Corpas

The Genome Analysis Centre
Norwich Research Park
Norwich, UK

Tel:  +44 1603 450 095
Fax: +44 1603 450 021
Web: http://goo.gl/ELtV4
Blog: http://manuelcorpas.com/

**Comment by jayjayjpg** [comment]
Maybe we could have a look into Keystone? Haven't any experience with that
yet, but just found it on a CMS comparison Blog Post: http://keystonejs.com/

**Comment by manuelcorpas** [comment]
My strong feeling is to stick to Drupal, frankly.

Manny

## 

Dr Manuel Corpas

The Genome Analysis Centre
Norwich Research Park
Norwich, UK

Tel:  +44 1603 450 095
Fax: +44 1603 450 021
Web: http://goo.gl/ELtV4
Blog: http://manuelcorpas.com/

**Comment by wilzbach** [comment]
Hey just a short reminder that once you switch from jekyll you will have to maintain and pay for the server plus you loose nice features like allowing everyone to edit an article. 

Best, 

## Seb 
- Sent from mobile. Please excuse any typos 
- Don't give spying a chance - use encryption
- Please use my PGP key @pgp.wilzba.ch/seb.asc

**Comment by manuelcorpas** [comment]
Thanks Seb for the useful comment
Manny

## 

Dr Manuel Corpas

The Genome Analysis Centre
Norwich Research Park
Norwich, UK

Tel:  +44 1603 450 095
Fax: +44 1603 450 021
Web: http://goo.gl/ELtV4
Blog: http://manuelcorpas.com/

**Comment by jayjayjpg** [comment]
@greenify @manuelcorpas Thanks for the input so far. I also think that our current setup is admirably easy to maintain on the developers' site, still it would be cool to enjoy the content editing features of a full CMS. 

I don't think we have to switch now, but I propose to do so in the near future. We'll discuss how easy it is to do that with Drupal once the TGAC site has been redone in our meeting on Monday.

**Comment by manuelcorpas** [comment]
@jessica Cool.
M

## 

Dr Manuel Corpas

The Genome Analysis Centre
Norwich Research Park
Norwich, UK

Tel:  +44 1603 450 095
Fax: +44 1603 450 021
Web: http://goo.gl/ELtV4
Blog: http://manuelcorpas.com/

**Comment by jayjayjpg** [comment]
@greenify @manuelcorpas @DennisSchwartz  Dennis and me found that Ghost CMS looks very promising and also seems to be easy to integrate with git and automatic deployment on openshift on code pushes. It's Node.js and Handlebars-based and allows easy Content Management via markdown and html: https://ghost.org/

**Comment by 4ndr01d3** [comment]
Hey there,
just to contribute a bit on the discussion just found this article
comparing some CMSs including Jekyll and drupal. Unfortunately doesn't
include any of the node alternatives.
My personal opinion is that drupal is a bit too much for what we need, and
Jekill wasn't a bad option at all, which makes me thing that an alternative
to consider is that instead of rebuilding the whole thing we can redesign
the site using the same technologies, making an effort on documenting how
to edit the content.
Cheers,
Gustavo.

**Comment by 4ndr01d3** [comment]
Ups... I forgot to put the link of the mentioned article:
http://coryetzkorn.com/blog/choosing-the-best-cms/

**Comment by DennisSchwartz** [comment]
Hey Gustavo! 

Thanks for your input. 
I will take a look at the article, but at first glance there is an argument against most of the ones listed.
We were choosing the CMS after the following criteria:
- Preferably free
- We can host our own instance with the code on Github (to keep it in the community)
- Flexibility in design (no rigid template systems)
- We are comfortable with the technology (esp. Jessica who does most of the work on this, also I personally don't like PHP :-P)
- No coding skills required to edit content (Manny has complained about having no access to the edu pages for example)

I have to say I'm quite happy with the current setup right now. If we get the template to work we could get somewhere with that.

Best,
Dennis

**Comment by DennisSchwartz** [comment]
Sorry wrong button there

**Comment by jayjayjpg** [comment]
Based website on an install of [Ghost CMS](https://ghost.org)
