### ISSUE TITLE
REDESIGN-16 - Re-Organize Contents on Home Page

### ISSUE THREAD

**Issue by jayjayjpg** [biojs/biojs.net#18]
Restructure the contents on the Biojs.net Homepage

The new design should focus on the two main conversion goals:  
- 1) Getting started/Tutorials 
- 2) Contributing
- create 4 semantic sections: 
  1) What is it (Header area)? 
  2) What can it do (Benefits / Video / Demo)?
  3) How can I start (links to Tutorials/Getting started guide)?
  4) How can I contribute (link to git / twitter / googlegroups or its own community page)?

Please include a couple of crosslinkings in the design to section 3) and 4) (maybe  add smooth scrolling functionality later in the implementation)

**Comment by manuelcorpas** [comment]
Great Stuff!

**Comment by jayjayjpg** [comment]
Closed by #23
