### ISSUE TITLE
REDESIGN-16 - Add sticky header to the Homepage

### ISSUE THREAD

**Issue by jayjayjpg** [biojs/biojs.net#19]
Could work similar to the one on the [Polymer Brandpage](https://www.polymer-project.org/1.0/)

**Comment by manuelcorpas** [comment]
I also like some aspects of the d3 page which provides a carrousel with the images of the library components in an eye-catchy way.

Cheers
M

**Comment by jayjayjpg** [comment]
@manuelcorpas Yes that's really a fancy design element - we'll check if we can have something similar in the header
