### ISSUE TITLE
Create new images for biojs.net main page

### ISSUE THREAD

**Issue by jayjayjpg** [biojs/biojs.net#25]
As discussed a couple of new images for the BioJS homepage would be necessary for our header and benefits section. Recent image ideas:
- close-up of a laptop with different BioJS components on screen 
- people discussing in front of laptop
- presentation in seminar room with BioJS visualizations on screen

**Comment by DennisSchwartz** [comment]
@jessica-jordan Is this still an issue?

**Comment by jayjayjpg** [comment]
I think that can closed - we only managed to check one of the three list items off the list of image suggestions, but it seems to be good enough :)
