### ISSUE TITLE
Documentation Link in Footer does not work

### ISSUE THREAD

**Issue by jajodiaraghav** [biojs/biojs.net#29]
In the footer section, under the heading "BioJS resources"

**Comment by DennisSchwartz** [comment]
Thanks for reporting it! It took a while but it's fixed now :)

Closed by https://github.com/biojs/biojs.net/pull/32

**Comment by DennisSchwartz** [comment]
@jajodiaraghav Sorry I just saw you actually had a PR as well 🙈 I merged it as well, thanks!
